### ISSUE TITLE
Using comma rather than space separation for option lists

### ISSUE THREAD

**Issue by excelero-joe** [Excelero/nvmesh-shell#11]
When using a comma to separate the names of two servers in the `-s` flag for volume creation, the command completes silently ignoring the bad selection format and uses an arbitrary pair of hosts matching the built-in selection algorithm of the API.  Desired function here would be to fail with a bad option return of some sort and optimally suggest space separation if such a condition could be easily detected as such.

**Comment by excelero-andreas** [comment]
The documentation clearly indicates to use space separated list of arguments throughout the CLI, not why a different character used as separator would solve the root cause issue.
I'll add validation, in general, to ensure that the required format is followed and a valid list is provided. This will also take care of issue #12

**Comment by excelero-joe** [comment]
This will not solve issue 12.  We tried to use a properly space separated list and that failed as well.  It seems to not pass the values for whatever reason.

**Comment by excelero-andreas** [comment]
It will

**Comment by excelero-andreas** [comment]
And fixed in v1.3.50
